kinopio-club/kinopio-client

- src/components/dialogs/About.vue
- src/consts.js
- src/router.js
- src/store/currentSpace.js
- src/store/store.js
adds routes
kinopio.club/blog -> open blog space
kinopio.club/discord
> Blog space

- src/components/SpaceDetailsInfo.vue
- src/components/dialogs/SpaceDetails.vue
- src/components/dialogs/SpaceFilters.vue
- src/store/currentUser.js
https://club.kinopio.club/t/calendar-widget-or-an-easier-way-to-navigate-between-journals/1365/6
> sort spaces by createdAt

- src/components/Box.vue
- src/consts.js
- src/store/currentBoxes.js
- src/store/currentCards.js
- src/utils.js
- src/views/Space.vue
- move card(s) near edge to expand box around them
- double click box resize to shrink to fit item contents
- fixes https://club.kinopio.club/t/boxes-can-be-dragged-further-up-than-cards/1374/3
> Expanding and shrinking boxes

- src/components/Header.vue
- src/components/Notifications.vue
- src/components/ReadOnlySpaceInfoBadges.vue
- src/components/SpaceDetailsInfo.vue
- src/components/SpaceUsersButton.vue
- src/components/TeamList.vue
- src/components/UserDetailsActions.vue
- src/components/dialogs/AddTeam.vue
- src/components/dialogs/SpaceDetails.vue
- src/components/dialogs/SpaceFilters.vue
- src/components/dialogs/SpaceUserList.vue
- src/components/dialogs/TeamDetails.vue
- src/components/dialogs/TeamPicker.vue
- src/components/dialogs/Teams.vue
- src/components/dialogs/UserDetailsInline.vue
- src/store/api.js
- src/store/currentUser.js
- src/store/store.js
- src/store/teams.js
- beta teams users w explicit permission can create teams
- when assigning team to space, choose which team 
- fix bug: cant rename team, input won't focus
- space filters list out teams to filter against (like users)
> Team2-2 release

- src/App.vue
- src/components/Card.vue
- src/components/Notifications.vue
- src/components/OtherCardPreview.vue
- src/components/OtherSpacePreview.vue
- src/components/OtherSpacePreviewCard.vue
- src/components/TeamInvitePreview.vue
- src/components/UrlPreviewCard.vue
- src/components/dialogs/CardDetails.vue
- src/router.js
- src/store/teams.js
- src/utils.js
> Team invite link in card

- src/components/KeyboardShortcutsHandler.vue
- src/components/Notifications.vue
- src/components/dialogs/BoxDetails.vue
- src/components/dialogs/KeyboardShortcuts.vue
- src/store/currentUser.js
- changelog notification: add changelog btn space link
> Disable keyboard shortcuts

- src/components/AlignAndDistribute.vue
- src/components/ItemCheckboxButton.vue
- src/components/dialogs/CardDetails.vue
- src/store/currentCards.js
Auto Align Cards Below [New]
When editing a card, all vertically aligned cards below it will stay aligned by shifting up or down to prevent overlapping
https://github.com/user-attachments/assets/9da9561c-9b18-4993-b3c6-df1df2e0e067
> Auto vertical align cards

- src/components/Export.vue
- src/components/Header.vue
- src/components/KeyboardShortcutsHandler.vue
- src/components/PrivacyIcon.vue
- src/components/ReadOnlySpaceInfoBadges.vue
- src/components/dialogs/MoveOrCopyItems.vue
- src/consts.js
- src/data/privacy.js
- src/store/currentBoxes.js
- src/store/currentCards.js
- src/store/currentConnections.js
- src/store/currentSpace.js
- src/store/store.js
- src/utils.js
https://github.com/user-attachments/assets/1895c22f-8b3c-49e4-96e7-7c1cd9ab2fca
> Copy paste boxes

- index.html
- src/components/AIImageGeneration.vue
- src/components/dialogs/AddSpace.vue
- src/store/analytics.js
- src/store/api.js
- src/store/store.js
- src/views/Space.vue
Almost done making a simple telemetry/analytics system to track specific events/clicks purely for the purpose of knowing what features can be removed. It’s basically a more secure/safer version of the plausible analytics script currently used (which’ll be removed).
The new system will be pretty transparent , with no user data sent, easy to see in the code, and every sent event logged in the console
> Add analytics

- src/assets/duplicate.svg
- src/components/Export.vue
- src/components/Import.vue
- src/components/ImportExportButton.vue
- src/components/Notifications.vue
- src/components/Preload.vue
- src/components/SpaceDetailsInfo.vue
- src/components/SpaceList.vue
- src/components/dialogs/ImportExport.vue
- src/components/dialogs/Share.vue
https://github.com/user-attachments/assets/065b77de-6907-4c86-bd66-87c17ee0f85e
also dry import/export button
> Template btn refactor

- src/components/Notifications.vue
- src/components/SnapGuideLines.vue
- src/store/store.js
- src/views/Space.vue
addresses the issue of trying to maintain alignment across a long drag distance
> Snap guide lines

- src/components/KeyboardShortcutsHandler.vue
- src/components/ScrollAndTouchHandler.vue
- src/components/subsections/UserSettingsControls.vue
- src/store/currentUser.js
- src/store/store.js
https://forum.kinopio.club/t/sync-mouse-pointer-with-canvas-movement-while-panning/1495/3
> fix jerky panning, improve panning speed/smoothness, remove need for panning speed setting

- src/components/dialogs/MultipleSelectedActions.vue
@bentsai not sure why , but i had to make to make a new pr based on your branch, so closing the old one and merging this
> Use the color of the first card when merging cards (pt2)

- src/App.vue
- src/components/Box.vue
- src/components/Card.vue
- src/components/CardList.vue
- src/components/CurrentConnection.vue
- src/components/Footer.vue
- src/components/KeyboardShortcutsHandler.vue
- src/components/SpaceCardList.vue
- src/components/dialogs/CardDetails.vue
- src/components/dialogs/FramePicker.vue
- src/components/dialogs/MultipleSelectedActions.vue
- src/components/dialogs/OtherCardDetails.vue
- src/components/dialogs/Search.vue
- src/components/dialogs/ShareCard.vue
- src/components/dialogs/TagDetails.vue
- src/components/dialogs/UserNotifications.vue
- src/components/sidebar/Inbox.vue
- src/components/sidebar/Minimap.vue
- src/components/sidebar/Text.vue
- src/data/frames.js
- src/store/currentCards.js
- src/store/currentSpace.js
- src/store/store.js
- src/store/upload.js
- src/views/Space.vue
https://github.com/user-attachments/assets/b86ccc05-b333-49bd-8159-6198341c06bb
https://forum.kinopio.club/t/card-link-doesnt-open-carddetails/1524/7
> Card focus animation

- src/components/BackgroundPreview.vue
- src/components/Box.vue
- src/components/ImageList.vue
- src/components/SpaceBackground.vue
- src/components/SpaceDetailsInfo.vue
- src/components/dialogs/BackgroundPicker.vue
- src/components/dialogs/BoxDetails.vue
- src/store/currentBoxes.js
- src/store/upload.js
- src/utils.js
- src/views/Space.vue
https://forum.kinopio.club/t/image-as-box-background/1381/10
> Box backgrounds

- src/components/dialogs/SpaceDetails.vue
- src/components/dialogs/SpaceFilters.vue
- src/store/currentUser.js
https://forum.kinopio.club/t/template-filter-in-spacelist/1540
> Template space filter

- src/components/Box.vue
- src/components/Card.vue
- src/components/ItemConnectorButton.vue
- src/components/dialogs/BoxDetails.vue
- src/store/currentBoxes.js
- src/store/currentConnections.js
- src/utils.js
- hides unused item connectors in presentation mode
- move box connector to right of box name
> Presentation mode connectors

- src/components/dialogs/BackgroundPicker.vue
Fixed the issue mentioned here: https://forum.kinopio.club/t/clearing-box-background-clears-space-tint-color/1542
https://github.com/user-attachments/assets/a77d06b2-3adf-4b43-b3bd-a440bc011f17
> Fix clearing box background clears space tint color

- src/components/Box.vue
- src/store/currentBoxes.js
- src/store/currentCards.js
https://forum.kinopio.club/t/ability-to-reorder-z-index-of-boxes/1539
> currentBoxes port z-index methods from currentCards

- package-lock.json
- package.json
- src/utils.js
- src/utils.test.js
- vite.config.js
Hello!
I hope this PR is helpful! I know I didn't discuss this anywhere, but I thought the changes were simple enough that I'd be okay if the PR was closed without merging. 😁
I noticed that some URLs weren't being parsed as I expected. I took the opportunity to add some minimal tests—it might have been a little presumptuous of me to have done so, and I'm happy to remove them if you don't want them!
(To be honest, I used a LLM to generate this code. I read every line of the tests it generated, and I skimmed the source code that it edited. I hand-edited some of the source code when it had trouble fixing the right thing.)
Also, I don't know how this would affect cards that were already created. I think I made the code a little stricter here and there (for example, `utils.queryString` no …
> `hidden=true` in URLs

- src/consts.js
This PR updates the subscription IDs on the client-side.
Please do not merge this yet. The new subscriptions and their localizations need to be reviewed by Apple first.
On the server-side there are no changes required.
I will mark this ready to be merged when I have updates from Apple.
> Update Apple subscriptions
